# https://github.com/cegepdefi

# Use an official base image
FROM atlassian/jira-software:latest

# Set environment variables
ENV ATL_JDBC_URL=jdbc:postgresql://jira_db:5432/jiradb
ENV ATL_JDBC_USER=jiradbuser
ENV ATL_JDBC_PASSWORD=jiradbpwd

# Expose the default Jira port
EXPOSE 8084
