# https://github.com/cegepdefi

version: '3'
services:
  jira_server:
    image: atlassian/jira-software:latest
    container_name: jira_server
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://jira_db:5432/jiradb
      - ATL_JDBC_USER=jiradbuser
      - ATL_JDBC_PASSWORD=jiradbpwd
    ports:
      - "8082:8080"
    depends_on:
      - jira_db
    volumes:
      - jira_server_data:/var/atlassian/application-data/jira

  jira_db:
    image: postgres:13
    container_name: jira_db
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: jiradbuser
      POSTGRES_PASSWORD: jiradbpwd
    volumes:
      - jira_db_data:/var/lib/postgresql/data

volumes:
  jira_server_data:
  jira_db_data:

networks:
  default:
    driver: bridge
